# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "nuget"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "C# - "
    directory: "./src"
    schedule:
      interval: "monthly"
    groups:
      "C#":
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "C# Tests - "
    directory: "./tests"
    schedule:
      interval: "monthly"
    groups:
      "C# Tests":
        patterns:
          - "*"
  - package-ecosystem: "pip"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Python - "
    directory: "./src/RoslynStone.GradioModule"
    schedule:
      interval: "monthly"
    groups:
      "Python":
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "GitHub Actions - "
    directory: ".github/workflows/"
    schedule:
      interval: "monthly"
    groups:
      "GitHub Actions":
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Dev Container - "
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      "Dev Container":
        patterns:
          - "*"
